### ISSUE TITLE
Create guidelines for participants

### ISSUE THREAD

**Issue by akhsin** [bppugm/icst-2018#21]
### Guidelines
- [x] EDAS for presenter
- [x] TTP for presenter
- [x] Attendant
### Payment procedure
- [x] Foreign participants
- [x] Domestic participants

**Comment by davieiycode** [comment]
change to eDas and TTP

**Comment by davieiycode** [comment]
### Images for EDAS guidebook (Account registration)
![1](https://user-images.githubusercontent.com/28292224/36659778-2c4d4c14-1b08-11e8-9832-e1d5f694783b.PNG)
![2](https://user-images.githubusercontent.com/28292224/36659783-33dd597e-1b08-11e8-806a-a314f1f9c27b.png)
![3](https://user-images.githubusercontent.com/28292224/36659788-3a1aa328-1b08-11e8-96e7-f3055cd9169b.png)
![4](https://user-images.githubusercontent.com/28292224/36659852-748a7416-1b08-11e8-9473-c235d84a9794.png)
![5](https://user-images.githubusercontent.com/28292224/36660101-75fdaace-1b09-11e8-88fc-900f9517aaaa.png)
![6](https://user-images.githubusercontent.com/28292224/36660228-fee3a17c-1b09-11e8-8189-fcae7782e048.png)
![7](https://user-images.githubusercontent.com/28292224/36660268-280bb526-1b0a-11e8-89ea-0eaabfc41557.png)
![8](https://user-images.githubusercontent.com/28292224/36660375-8342b624-1b0a-11e8-90b7-36f1c45a23d0.png)

**Comment by davieiycode** [comment]
### Images for non-presenter guidebook
![5](https://user-images.githubusercontent.com/28292224/36963384-8a34e21a-2085-11e8-8377-0530d66b1c1e.png)
![4](https://user-images.githubusercontent.com/28292224/36963385-8a68a08c-2085-11e8-9321-18bcef003084.png)
![3](https://user-images.githubusercontent.com/28292224/36963386-8a9ae33a-2085-11e8-9c39-6e2674c7ce08.png)
![2](https://user-images.githubusercontent.com/28292224/36963387-8ace3cd0-2085-11e8-831c-4dad468a5310.png)
![1](https://user-images.githubusercontent.com/28292224/36963389-8afffc84-2085-11e8-933c-62a05870ab06.png)
![6](https://user-images.githubusercontent.com/28292224/36963383-89d75be0-2085-11e8-9095-7695d5896aa4.png)
