### ISSUE TITLE
image for EDAS and TTP card in submission.html

### ISSUE THREAD

**Issue by akhsin** [bppugm/icst-2018#40]
@davieiycode

**Comment by davieiycode** [comment]
![edas](https://user-images.githubusercontent.com/28292224/36408368-86cec274-1637-11e8-9eef-ca8efbdb814e.png)
![ttp](https://user-images.githubusercontent.com/28292224/36408369-8713e3c2-1637-11e8-8191-a48dbf8c7446.png)

**Comment by davieiycode** [comment]
new images for submission card
![edas](https://user-images.githubusercontent.com/28292224/36655055-f76e23d4-1af2-11e8-9268-6a2b1a7bed00.png)
![ttp](https://user-images.githubusercontent.com/28292224/36655057-f7e229dc-1af2-11e8-85ec-ea4c250258fe.png)
![non-presenter](https://user-images.githubusercontent.com/28292224/36655056-f7acb8f6-1af2-11e8-950f-d3a52d824257.png)
