### ISSUE TITLE
Add payment confirmation

### ISSUE THREAD

**Issue by akhsin** [bppugm/icst-2018#90]
Dear @sulish dan @febriyanyoga  , 
Ku nambah halaman payment confirmation. ada 2: untuk presenter dan non presenter.
1. payment-confirmation-presenter.html tolong ditambahkan ke dropdown di bawah presenter (di bawahnya payment procedure)
2. 1. payment-confirmation-non-presenter.html tolong ditambahkan ke dropdown di bawah non-presenter (di bawahnya payment procedure)

**Comment by sulish** [comment]
Done. pull request nunggu tutorial page nya kelar.
